#source 'https://rubygems.org'
#gem 'glycobook', '0.0.3'


# Bundlerのexecコマンドを使用してスクリプトを実行
require 'bundler/inline'

gemfile do
  gem 'glycobook', path: '/Users/skit/src/gitlab/glycobook/glycobook/glycobook-0.0.4.gem'
end

# スクリプトの実行
require 'glycobook'

GlycoBook.init

